### PR TITLE
Deploy V2 site

### PR DESCRIPTION
**Pull request by flynnduism**
Merging this PR will deploy the site updates at `v2.brigade.sh` to the prod site at `brigade.sh`

### CODE REVIEW

**Review by krancour — APPROVED** [review]

**Comment by krancour** [comment]
LGTM, but there's a Gemfile.lock conflict?

**Comment by flynnduism** [comment]
Got the `gemfile.lock` conflict resolved, but seeing another blocker:

> The base branch requires all commits to be signed.

DCO is green though, not sure where the unsigned commit is?

**Comment by krancour** [comment]
> DCO is green though, not sure where the unsigned commit is?

@flynnduism "sign" is overloaded, unfortunately. It's complaining that your commits aren't signed with your PGP key.

Probably you had that all set up previously and got a new laptop when you changed jobs recently?

Even older commits in the `v2` branch that might have been made before switching jobs got "unsigned" if they were affected by any recent rebase.

I'll temporarily lift the signature requirement.

**Comment by krancour** [comment]
@flynnduism this should be mergeable now.

**Comment by krancour** [comment]
@flynnduism thanks for all the hard work on this! @vdice you too, with the content changes!

**Pull request merged**
