### PR TITLE
fixes element overlap

### LINKED ISSUE #64: Certain screen elements still overlap
Screen Shot 2022-03-02 at 10 02 44 AM

### PR DESCRIPTION
**Pull request by GermaVinsmoke**
Fixes #64 

Btw, can you help me with joining the Slack channel because it's not allowing me, says "doesn’t have an account on this workspace"

Signed-off-by: Vaibhav Dangra <vaibhav1180@gmail.com>

### CODE REVIEW

**Comment by krancour** [comment]
Hi @GermaVinsmoke. Thanks for the contribution! I'll be able to review on Monday morning.

As for Slack... our channel is part of the Kubernetes Slack workspace, so visit https://slack kubernetes.io first to get an invite.

I think we need to do something on our end to make this more clear because this has tripped up a lot of people lately.

**Comment by krancour** [comment]
@GermaVinsmoke this doesn't seem to fix the issue.

See [preview](https://deploy-preview-66--brigade-sh.netlify.app/).

**Comment by GermaVinsmoke** [comment]
> @GermaVinsmoke this doesn't seem to fix the issue.
> 
> See [preview](https://deploy-preview-66--brigade-sh.netlify.app/).

Sorry for that, changed the value in some other CSS block.

**Comment by flynnduism** [comment]
> Also pinging @flynnduism for review since he is far more expert on CSS than myself.

Thanks @GermaVinsmoke. The site [deploy preview](https://deploy-preview-66--brigade-sh.netlify.app/) looks good, thank you (pending DCO signoff).

**Review by flynnduism — APPROVED** [review]

**Comment by krancour** [comment]
Thanks for reviewing @flynnduism!

Still needs DCO signoff.

**Comment by GermaVinsmoke** [comment]
Closing this one because it got way too messy :'(

**Pull request closed without merging**
